#!/bin/bash -ex
# Meson wrapper for Chakra Linux packaging

exec meson setup \
  --prefix         /usr \
  --libdir         /usr/lib \
  --libexecdir     /usr/lib \
  --bindir         /usr/bin \
  --sbindir        /usr/bin \
  --includedir     /usr/include \
  --datadir        /usr/share \
  --mandir         /usr/share/man \
  --infodir        /usr/share/info \
  --localedir      /usr/share/locale \
  --sysconfdir     /etc \
  --localstatedir  /var \
  --sharedstatedir /var/lib \
  --buildtype      plain \
  --auto-features  enabled \
  --warnlevel      2 \
  --wrap-mode      nodownload \
  -D               b_lto=true \
  -D               b_pie=true \
  "$@"
